#!/usr/bin/env python3
"""
Create a new prompt.

Usage:
    python prompt_create.py --name <prompt-name> --description "What this prompt does" [--project <project>]
"""

import argparse
import os
import sys
from datetime import datetime
from pathlib import Path

import yaml


def find_prompts_dir(project_name: str = None) -> Path:
    """Find the prompts directory."""
    script_dir = Path(__file__).parent
    nexus_root = script_dir.parent.parent.parent.parent

    # If project specified, search for it
    if project_name:
        projects_dir = nexus_root / "02-projects"
        for folder in projects_dir.iterdir():
            if folder.is_dir() and project_name.lower() in folder.name.lower():
                return folder / "02-resources" / "prompts"

    # Otherwise, try to find from current working directory
    cwd = Path.cwd()
    for parent in [cwd] + list(cwd.parents):
        prompts_dir = parent / "02-resources" / "prompts"
        if prompts_dir.exists():
            return prompts_dir

    return None


def load_config(prompts_dir: Path) -> dict:
    """Load the prompt config."""
    config_file = prompts_dir / ".prompt-config.yaml"
    if not config_file.exists():
        return None
    with open(config_file, 'r') as f:
        return yaml.safe_load(f)


def save_config(prompts_dir: Path, config: dict):
    """Save the prompt config."""
    config_file = prompts_dir / ".prompt-config.yaml"
    with open(config_file, 'w') as f:
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)


def regenerate_registry(prompts_dir: Path, config: dict):
    """Regenerate the REGISTRY.md file."""
    project_name = config.get('project', 'Project')
    prompts = config.get('prompts', {})

    # Build table rows
    table_rows = []
    details = []

    for name, data in prompts.items():
        current = data.get('current', 'v1')
        versions = data.get('versions', {})
        version_count = len(versions)

        # Get last updated date
        last_date = "N/A"
        if versions:
            dates = [v.get('date', '') for v in versions.values()]
            last_date = max(dates) if dates else "N/A"

        table_rows.append(f"| [{name}](#{name}) | {current} | {version_count} | {last_date} |")

        # Build details section
        detail = f"## {name}\n\n"
        detail += f"**Description**: {data.get('description', 'N/A')}\n\n"
        detail += f"**Current Production**: {current}\n\n"
        detail += "| Version | Date | Ticket | Change |\n"
        detail += "|---------|------|--------|--------|\n"

        for ver, ver_data in versions.items():
            ticket = ver_data.get('ticket') or '-'
            change = ver_data.get('change', '-')
            date = ver_data.get('date', '-')
            marker = " **[CURRENT]**" if ver == current else ""
            detail += f"| {ver}{marker} | {date} | {ticket} | {change} |\n"

        details.append(detail)

    # Build registry content
    table_content = "\n".join(table_rows) if table_rows else "| *No prompts yet* | - | - | - |"
    details_content = "\n---\n\n".join(details) if details else "*No prompts created yet.*"

    registry_content = f"""# {project_name} Prompt Registry

> Auto-generated by prompt-versioning skill. Do not edit manually.
>
> **Last Updated**: {datetime.now().strftime('%Y-%m-%d %H:%M')}

---

## Quick Reference

| Prompt | Current | Versions | Last Updated |
|--------|---------|----------|--------------|
{table_content}

---

{details_content}

---

## Commands

```bash
# List all prompts
python prompt_list.py

# Get current version of a prompt
python prompt_get.py --name <prompt-name>

# Create new version
python prompt_version.py --name <prompt-name> --ticket <LINEAR-ID> --change "description"

# Compare versions
python prompt_diff.py --name <prompt-name> --v1 v1 --v2 v2

# Set production version
python prompt_set_current.py --name <prompt-name> --version <vX>
```
"""

    registry_file = prompts_dir / "REGISTRY.md"
    with open(registry_file, 'w') as f:
        f.write(registry_content)


def create_prompt(prompts_dir: Path, name: str, description: str, content: str = None) -> dict:
    """Create a new prompt."""
    config = load_config(prompts_dir)
    if not config:
        print("[ERROR] Prompt versioning not initialized. Run prompt_init.py first.")
        sys.exit(1)

    # Check if prompt already exists
    if name in config.get('prompts', {}):
        print(f"[ERROR] Prompt '{name}' already exists. Use prompt_version.py to create a new version.")
        sys.exit(1)

    # Create prompt directory
    prompt_dir = prompts_dir / name
    prompt_dir.mkdir(exist_ok=True)

    # Create v1
    today = datetime.now().strftime('%Y-%m-%d')
    prompt_content = content or "# Add your prompt content here\n"

    prompt_file_content = f"""# {name}

> **Version**: v1
> **Created**: {today}
> **Ticket**: -
> **Change**: Initial version
> **Beam Node**: -

---

## Prompt

```
{prompt_content}
```

---

## Input Variables

| Variable | Type | Description |
|----------|------|-------------|
| | | |

---

## Output Format

```json
{{

}}
```

---

## Test Cases

| Scenario | Input | Expected Output |
|----------|-------|-----------------|
| | | |

---

## Notes

- Initial version
"""

    v1_file = prompt_dir / "v1.md"
    with open(v1_file, 'w') as f:
        f.write(prompt_file_content)

    # Update config
    if 'prompts' not in config:
        config['prompts'] = {}

    config['prompts'][name] = {
        'description': description,
        'current': 'v1',
        'beam_node_id': None,
        'versions': {
            'v1': {
                'date': today,
                'ticket': None,
                'change': 'Initial version'
            }
        }
    }

    save_config(prompts_dir, config)
    regenerate_registry(prompts_dir, config)

    return config['prompts'][name]


def main():
    parser = argparse.ArgumentParser(description='Create a new prompt')
    parser.add_argument('--name', required=True, help='Prompt name (use node name)')
    parser.add_argument('--description', required=True, help='What this prompt does')
    parser.add_argument('--project', help='Project name (optional)')
    parser.add_argument('--content', help='Initial prompt content')
    args = parser.parse_args()

    prompts_dir = find_prompts_dir(args.project)

    if not prompts_dir or not prompts_dir.exists():
        print("[ERROR] Prompts directory not found.")
        print("Run prompt_init.py first, or use --project to specify the project.")
        sys.exit(1)

    print(f"[INFO] Creating prompt '{args.name}' in: {prompts_dir}")

    result = create_prompt(prompts_dir, args.name, args.description, args.content)

    print(f"\n[SUCCESS] Created prompt: {args.name}")
    print(f"   File: {prompts_dir / args.name / 'v1.md'}")
    print(f"   Current: v1")
    print(f"\nEdit the prompt file, then use prompt_version.py for future changes.")


if __name__ == "__main__":
    main()
