#!/usr/bin/env python3
"""
Initialize prompt versioning in a project.

Usage:
    python prompt_init.py --project <project-name> [--path <project-path>]
"""

import argparse
import os
import sys
from datetime import datetime
from pathlib import Path

import yaml


def get_project_path(project_name: str, custom_path: str = None) -> Path:
    """Get the project path."""
    if custom_path:
        return Path(custom_path)

    # Default: look in 02-projects folder relative to nexus root
    script_dir = Path(__file__).parent
    nexus_root = script_dir.parent.parent.parent.parent

    # Search for project folder
    projects_dir = nexus_root / "02-projects"
    if projects_dir.exists():
        for folder in projects_dir.iterdir():
            if folder.is_dir() and project_name.lower() in folder.name.lower():
                return folder

    return None


def init_prompt_versioning(project_name: str, project_path: Path) -> dict:
    """Initialize prompt versioning in a project."""

    prompts_dir = project_path / "02-resources" / "prompts"
    config_file = prompts_dir / ".prompt-config.yaml"

    # Check if already initialized
    if config_file.exists():
        print(f"[WARNING] Prompt versioning already initialized at {prompts_dir}")
        with open(config_file, 'r') as f:
            return yaml.safe_load(f)

    # Create directory
    prompts_dir.mkdir(parents=True, exist_ok=True)

    # Create config
    config = {
        'project': project_name,
        'created': datetime.now().strftime('%Y-%m-%d'),
        'prompts': {}
    }

    with open(config_file, 'w') as f:
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)

    # Create initial registry
    registry_file = prompts_dir / "REGISTRY.md"
    registry_content = f"""# {project_name} Prompt Registry

> Auto-generated by prompt-versioning skill.
>
> **Last Updated**: {datetime.now().strftime('%Y-%m-%d %H:%M')}

---

## Quick Reference

| Prompt | Current | Versions | Last Updated |
|--------|---------|----------|--------------|
| *No prompts yet* | - | - | - |

---

## Getting Started

```bash
# Create your first prompt
python prompt_create.py --name <node-name> --description "What this prompt does"

# List all prompts
python prompt_list.py
```
"""

    with open(registry_file, 'w') as f:
        f.write(registry_content)

    return config


def main():
    parser = argparse.ArgumentParser(description='Initialize prompt versioning')
    parser.add_argument('--project', required=True, help='Project name')
    parser.add_argument('--path', help='Custom project path')
    args = parser.parse_args()

    # Find project path
    project_path = get_project_path(args.project, args.path)

    if not project_path or not project_path.exists():
        print(f"[ERROR] Project not found: {args.project}")
        print("Use --path to specify the project directory")
        sys.exit(1)

    print(f"[INFO] Initializing prompt versioning in: {project_path}")

    config = init_prompt_versioning(args.project, project_path)

    prompts_dir = project_path / "02-resources" / "prompts"
    print(f"\n[SUCCESS] Prompt versioning initialized!")
    print(f"   Config: {prompts_dir / '.prompt-config.yaml'}")
    print(f"   Registry: {prompts_dir / 'REGISTRY.md'}")
    print(f"\nNext: Create your first prompt with:")
    print(f"   python prompt_create.py --name <node-name> --description \"...\"")


if __name__ == "__main__":
    main()
