#!/usr/bin/env python3
"""
Set the current production version of a prompt.

Usage:
    python prompt_set_current.py --name <prompt-name> --version <vX>
"""

import argparse
import sys
from datetime import datetime
from pathlib import Path

import yaml


def find_prompts_dir(project_name: str = None) -> Path:
    """Find the prompts directory."""
    script_dir = Path(__file__).parent
    nexus_root = script_dir.parent.parent.parent.parent

    if project_name:
        projects_dir = nexus_root / "02-projects"
        for folder in projects_dir.iterdir():
            if folder.is_dir() and project_name.lower() in folder.name.lower():
                return folder / "02-resources" / "prompts"

    cwd = Path.cwd()
    for parent in [cwd] + list(cwd.parents):
        prompts_dir = parent / "02-resources" / "prompts"
        if prompts_dir.exists():
            return prompts_dir

    return None


def load_config(prompts_dir: Path) -> dict:
    """Load the prompt config."""
    config_file = prompts_dir / ".prompt-config.yaml"
    if not config_file.exists():
        return None
    with open(config_file, 'r') as f:
        return yaml.safe_load(f)


def save_config(prompts_dir: Path, config: dict):
    """Save the prompt config."""
    config_file = prompts_dir / ".prompt-config.yaml"
    with open(config_file, 'w') as f:
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)


def regenerate_registry(prompts_dir: Path, config: dict):
    """Regenerate the REGISTRY.md file."""
    project_name = config.get('project', 'Project')
    prompts = config.get('prompts', {})

    table_rows = []
    details = []

    for name, data in prompts.items():
        current = data.get('current', 'v1')
        versions = data.get('versions', {})
        version_count = len(versions)

        last_date = "N/A"
        if versions:
            dates = [v.get('date', '') for v in versions.values()]
            last_date = max(dates) if dates else "N/A"

        table_rows.append(f"| [{name}](#{name}) | {current} | {version_count} | {last_date} |")

        detail = f"## {name}\n\n"
        detail += f"**Description**: {data.get('description', 'N/A')}\n\n"
        detail += f"**Current Production**: {current}\n\n"
        detail += "| Version | Date | Ticket | Change |\n"
        detail += "|---------|------|--------|--------|\n"

        for ver, ver_data in versions.items():
            ticket = ver_data.get('ticket') or '-'
            change = ver_data.get('change', '-')
            date = ver_data.get('date', '-')
            marker = " **[CURRENT]**" if ver == current else ""
            detail += f"| {ver}{marker} | {date} | {ticket} | {change} |\n"

        details.append(detail)

    table_content = "\n".join(table_rows) if table_rows else "| *No prompts yet* | - | - | - |"
    details_content = "\n---\n\n".join(details) if details else "*No prompts created yet.*"

    registry_content = f"""# {project_name} Prompt Registry

> Auto-generated by prompt-versioning skill. Do not edit manually.
>
> **Last Updated**: {datetime.now().strftime('%Y-%m-%d %H:%M')}

---

## Quick Reference

| Prompt | Current | Versions | Last Updated |
|--------|---------|----------|--------------|
{table_content}

---

{details_content}

---

## Commands

```bash
# List all prompts
python prompt_list.py

# Get current version of a prompt
python prompt_get.py --name <prompt-name>

# Create new version
python prompt_version.py --name <prompt-name> --ticket <LINEAR-ID> --change "description"

# Compare versions
python prompt_diff.py --name <prompt-name> --v1 v1 --v2 v2

# Set production version
python prompt_set_current.py --name <prompt-name> --version <vX>
```
"""

    registry_file = prompts_dir / "REGISTRY.md"
    with open(registry_file, 'w') as f:
        f.write(registry_content)


def set_current(prompts_dir: Path, name: str, version: str) -> dict:
    """Set the current production version."""
    config = load_config(prompts_dir)
    if not config:
        print("[ERROR] Prompt versioning not initialized.")
        sys.exit(1)

    if name not in config.get('prompts', {}):
        print(f"[ERROR] Prompt '{name}' not found.")
        sys.exit(1)

    prompt_data = config['prompts'][name]
    versions = prompt_data.get('versions', {})

    if version not in versions:
        print(f"[ERROR] Version '{version}' not found for '{name}'.")
        print("\nAvailable versions:")
        for v in versions.keys():
            print(f"  - {v}")
        sys.exit(1)

    # Check file exists
    prompt_file = prompts_dir / name / f"{version}.md"
    if not prompt_file.exists():
        print(f"[ERROR] Prompt file not found: {prompt_file}")
        sys.exit(1)

    old_current = prompt_data.get('current', 'v1')
    prompt_data['current'] = version

    save_config(prompts_dir, config)
    regenerate_registry(prompts_dir, config)

    return {'old': old_current, 'new': version}


def main():
    parser = argparse.ArgumentParser(description='Set production version of a prompt')
    parser.add_argument('--name', required=True, help='Prompt name')
    parser.add_argument('--version', required=True, help='Version to set as current (e.g., v2)')
    parser.add_argument('--project', help='Project name (optional)')
    args = parser.parse_args()

    prompts_dir = find_prompts_dir(args.project)

    if not prompts_dir or not prompts_dir.exists():
        print("[ERROR] Prompts directory not found.")
        sys.exit(1)

    result = set_current(prompts_dir, args.name, args.version)

    print(f"\n[SUCCESS] Updated '{args.name}' production version")
    print(f"   Previous: {result['old']}")
    print(f"   Current:  {result['new']}")
    print(f"\n   Registry updated: {prompts_dir / 'REGISTRY.md'}")


if __name__ == "__main__":
    main()
